#!/usr/bin/perl 

use strict;
use warnings;

use Dist::Release;
use Getopt::Long;

my %options;
GetOptions( \%options, 
    'list!',
    'action=s@',
    'check=s@',
    'checks!',
    'doit!',
);

my %args;
if ( $options{action} and @{$options{action}} ) {
    $args{actions} = $options{action};
}
if ( $options{check} and @{$options{check}} ) {
    $args{checks} = $options{check};
}

$args{check_only}=1 if  $options{checks};
$args{pretend}= !$options{doit};

my $rel = Dist::Release->new( %args );

if ( $options{list} ) {
    $rel->print_steps;
    exit;
}


$rel->run;

__END__


=over

=item --list

Prints out all the checks are actions that would be performed and exits.

=back
